# Generated by Django 3.0.6 on 2020-06-06 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinashe_projects', '0002_auto_20200606_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(upload_to='tinashe_projects/static/about'),
        ),
        migrations.AlterField(
            model_name='recentwork',
            name='image',
            field=models.ImageField(upload_to='tinashe_projects/static/works'),
        ),
    ]
